apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: notification-service
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: otniel217/ecom-notification-service:latest
          ports:
            - containerPort: 8084
          env:
            # Base de données et Messaging
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/notification"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            
            # Configuration Redis
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"

            # Service Discovery (Eureka)
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-registry:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "384Mi"

          # Probes : Crucial ici car il y a 3 dépendances (DB, Cache, Broker)
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 45 # Temps de démarrage légèrement plus long
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 10