apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: order-service
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: otniel217/ecom-order-service:latest
          ports:
            - containerPort: 8081
          env:
            # Base de données PostgreSQL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/order_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres" # Rappel : à mettre dans un Secret pour la prod !
            
            # Messaging Kafka
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

            # Service Discovery (Eureka)
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-registry:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "384Mi"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10